#ifndef SL_COMPONENT_CATALOG_H
#define SL_COMPONENT_CATALOG_H

// APIs present in project
#define SL_CATALOG_DEVICE_INIT_NVIC_PRESENT
#define SL_CATALOG_MPU_PRESENT
#define SL_CATALOG_MX25_FLASH_SHUTDOWN_USART_PRESENT
#define SL_CATALOG_OPENTHREAD_CLI_PRESENT
#define SL_CATALOG_OPENTHREAD_STACK_PRESENT
#define SL_CATALOG_POWER_MANAGER_PRESENT

#endif // SL_COMPONENT_CATALOG_H
